-- =====================================================
-- STAFF MANAGEMENT & RBAC MIGRATION
-- Description: Add staff role and permissions table
-- =====================================================

-- 1. Add 'staff' to user_role_enum
-- Note: 'ALTER TYPE' cannot be executed inside a transaction block in some Postgres versions.
-- We use a DO block or just run it directly.
ALTER TYPE user_role_enum ADD VALUE IF NOT EXISTS 'staff';

-- 2. Create business_staff table
CREATE TABLE IF NOT EXISTS business_staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    
    -- Full name for local identification in the shop context
    staff_name VARCHAR(255) NOT NULL,
    
    -- Permissions as JSONB for flexibility
    -- Format: {"pos": true, "stock": false, "reports": false, "settings": false}
    permissions JSONB DEFAULT '{"pos": true, "stock": false, "reports": false, "settings": false}'::jsonb,
    
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Ensure a user is only linked once to a business
    UNIQUE(business_id, user_id)
);

-- 3. Add Updated At Trigger
CREATE TRIGGER update_business_staff_updated_at
    BEFORE UPDATE ON business_staff
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 4. Indexes
CREATE INDEX IF NOT EXISTS idx_business_staff_business_id ON business_staff(business_id);
CREATE INDEX IF NOT EXISTS idx_business_staff_user_id ON business_staff(user_id);

-- 5. RLS (Initial Placeholder - Needs to be refined based on actual business logic)
-- Enable RLS
ALTER TABLE business_staff ENABLE ROW LEVEL SECURITY;

-- Owner Policy: Can manage staff for their own business
CREATE POLICY "Owners can manage their own staff" ON business_staff
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM businesses b
            WHERE b.id = business_staff.business_id
            AND b.user_id = (SELECT u.id FROM users u WHERE u.auth_id = auth.uid())
        )
    );

-- Staff Policy: Can see their own staff record
CREATE POLICY "Staff can see their own data" ON business_staff
    FOR SELECT
    USING (
        user_id = (SELECT u.id FROM users u WHERE u.auth_id = auth.uid())
    );
