-- DATABASE SCHEMA - KASIR UMKM APP (PostgreSQL / Supabase Version)

-- =====================================================
-- DATABASE SCHEMA: KASIR UMKM
-- Version: 1.1 (Modified for Super Admin & UUIDs)
-- Description: Complete database schema for POS system (PostgreSQL compatible)
-- =====================================================

-- Enable necessary extensions
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================
-- ENUM TYPES
-- =====================================================

CREATE TYPE business_type_enum AS ENUM ('warung_sembako', 'kedai_kopi', 'warteg', 'toko_kelontong', 'lainnya');
CREATE TYPE hpp_mode_enum AS ENUM ('sederhana', 'akurat');
CREATE TYPE member_level_enum AS ENUM ('baru', 'silver', 'gold', 'platinum');
CREATE TYPE movement_type_enum AS ENUM ('purchase', 'sale', 'adjustment', 'return', 'damage');
CREATE TYPE payment_method_enum AS ENUM ('cash', 'qris', 'transfer', 'ewallet', 'debit');
CREATE TYPE payment_status_enum AS ENUM ('pending', 'paid', 'cancelled');
CREATE TYPE recurrence_period_enum AS ENUM ('daily', 'monthly', 'yearly');
CREATE TYPE notification_type_enum AS ENUM ('stock_alert', 'report_reminder', 'payment_due', 'system', 'promotion');
CREATE TYPE discount_type_enum AS ENUM ('percentage', 'fixed');
CREATE TYPE member_points_type_enum AS ENUM ('earned', 'redeemed', 'expired', 'adjustment');
CREATE TYPE user_role_enum AS ENUM ('super_admin', 'shop_owner');

-- =====================================================
-- FUNCTIONS FOR UPDATED_AT
-- =====================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- =====================================================
-- 1. TABEL USERS & AUTHENTICATION
-- =====================================================

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), -- Changed to UUID for Supabase Native feel
    auth_id UUID REFERENCES auth.users(id), -- Link to Supabase Auth
    
    email VARCHAR(255) UNIQUE, -- Added for Super Admin login
    role user_role_enum DEFAULT 'shop_owner', -- Role distinction
    
    activation_code VARCHAR(20) UNIQUE, -- Nullable now (Admin doesn't need it)
    phone_number VARCHAR(20) UNIQUE, -- Nullable now
    phone_verified BOOLEAN DEFAULT FALSE,
    otp_code VARCHAR(6),
    otp_expires_at TIMESTAMP WITH TIME ZONE,
    
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_users_activation_code ON users(activation_code);
CREATE INDEX idx_users_phone_number ON users(phone_number);
CREATE INDEX idx_users_auth_id ON users(auth_id);
CREATE INDEX idx_users_email ON users(email);

-- =====================================================
-- 2. TABEL BUSINESS/USAHA
-- =====================================================

CREATE TABLE businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- References UUID
    business_name VARCHAR(255) NOT NULL,
    business_type business_type_enum NOT NULL,
    address TEXT,
    phone VARCHAR(20),
    email VARCHAR(100),
    logo_url VARCHAR(255),
    
    -- HPP Mode
    hpp_mode hpp_mode_enum DEFAULT 'sederhana',
    
    -- Settings
    tax_percentage DECIMAL(5,2) DEFAULT 0.00,
    currency VARCHAR(3) DEFAULT 'IDR',
    timezone VARCHAR(50) DEFAULT 'Asia/Jakarta',

    -- Loyalty Settings
    point_value_requirement INT DEFAULT 10000,
    discount_silver_percent DECIMAL(5,2) DEFAULT 5.00,
    discount_gold_percent DECIMAL(5,2) DEFAULT 10.00,
    discount_platinum_percent DECIMAL(5,2) DEFAULT 15.00,
    
    -- Status
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_businesses_updated_at
    BEFORE UPDATE ON businesses
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_businesses_user_id ON businesses(user_id);

-- =====================================================
-- 3. TABEL CATEGORIES (Kategori Barang)
-- =====================================================

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    icon VARCHAR(50),
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_categories_updated_at
    BEFORE UPDATE ON categories
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_categories_business_id ON categories(business_id);

-- =====================================================
-- 4. TABEL PRODUCTS (Barang Dagangan)
-- =====================================================

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    
    -- Basic Info
    name VARCHAR(255) NOT NULL,
    sku VARCHAR(100) UNIQUE,
    barcode VARCHAR(100),
    description TEXT,
    image_url VARCHAR(255),
    
    -- Pricing
    purchase_price DECIMAL(15,2) NOT NULL DEFAULT 0.00, -- Harga beli
    selling_price DECIMAL(15,2) NOT NULL DEFAULT 0.00,  -- Harga jual
    
    -- Stock
    stock_quantity DECIMAL(10,2) DEFAULT 0.00,
    unit VARCHAR(20) DEFAULT 'pcs', -- pcs, botol, karton, kg, dll
    min_stock DECIMAL(10,2) DEFAULT 5.00, -- Minimum stock alert
    
    -- Additional
    is_favorite BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_products_business_id ON products(business_id);
CREATE INDEX idx_products_category_id ON products(category_id);
CREATE INDEX idx_products_barcode ON products(barcode);
CREATE INDEX idx_products_sku ON products(sku);
CREATE INDEX idx_products_name ON products(name);
CREATE INDEX idx_products_business_active ON products(business_id, is_active);

-- =====================================================
-- 5. TABEL STOCK MOVEMENTS (Riwayat Stok)
-- =====================================================

CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    
    -- Movement Details
    movement_type movement_type_enum NOT NULL,
    quantity DECIMAL(10,2) NOT NULL,
    
    -- Pricing (untuk HPP calculation)
    purchase_price_per_unit DECIMAL(15,2),
    selling_price_per_unit DECIMAL(15,2),
    
    -- Reference
    reference_type VARCHAR(50), -- 'transaction', 'purchase_order', 'adjustment'
    reference_id BIGINT,
    
    -- Stock Before/After
    stock_before DECIMAL(10,2),
    stock_after DECIMAL(10,2),
    
    notes TEXT,
    movement_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID -- References user_id (UUID)
);

CREATE INDEX idx_stock_movements_business_id ON stock_movements(business_id);
CREATE INDEX idx_stock_movements_product_id ON stock_movements(product_id);
CREATE INDEX idx_stock_movements_movement_date ON stock_movements(movement_date);
CREATE INDEX idx_stock_movements_reference ON stock_movements(reference_type, reference_id);
CREATE INDEX idx_stock_movements_product_date ON stock_movements(product_id, movement_date);

-- =====================================================
-- 6. TABEL PURCHASE ORDERS (Pembelian Stok)
-- =====================================================

CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    
    -- Order Info
    po_number VARCHAR(50) UNIQUE NOT NULL,
    supplier_name VARCHAR(255),
    purchase_date DATE NOT NULL,
    
    -- Amounts
    total_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_purchase_orders_updated_at
    BEFORE UPDATE ON purchase_orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_purchase_orders_business_id ON purchase_orders(business_id);
CREATE INDEX idx_purchase_orders_po_number ON purchase_orders(po_number);
CREATE INDEX idx_purchase_orders_purchase_date ON purchase_orders(purchase_date);

CREATE TABLE purchase_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    
    quantity DECIMAL(10,2) NOT NULL,
    purchase_price DECIMAL(15,2) NOT NULL,
    subtotal DECIMAL(15,2) NOT NULL
);

CREATE INDEX idx_purchase_order_items_po_id ON purchase_order_items(purchase_order_id);
CREATE INDEX idx_purchase_order_items_product_id ON purchase_order_items(product_id);

-- =====================================================
-- 7. TABEL MEMBERS/CUSTOMERS
-- =====================================================

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    
    -- Personal Info
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(100),
    address TEXT,
    
    -- Membership
    member_level member_level_enum DEFAULT 'baru',
    join_date DATE NOT NULL,
    
    -- Points & Stats
    total_points INT DEFAULT 0,
    total_transactions INT DEFAULT 0,
    total_spending DECIMAL(15,2) DEFAULT 0.00,
    
    -- Preferences
    discount_percentage DECIMAL(5,2) DEFAULT 0.00,
    notes TEXT,
    
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_members_updated_at
    BEFORE UPDATE ON members
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_members_business_id ON members(business_id);
CREATE INDEX idx_members_phone ON members(phone);
CREATE INDEX idx_members_name ON members(name);

-- =====================================================
-- 8. TABEL TRANSACTIONS (Transaksi Penjualan)
-- =====================================================

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    member_id BIGINT REFERENCES members(id) ON DELETE SET NULL,
    
    -- Transaction Info
    transaction_number VARCHAR(50) UNIQUE NOT NULL,
    transaction_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Payment Details
    payment_method payment_method_enum NOT NULL,
    payment_status payment_status_enum DEFAULT 'paid',
    
    -- Amounts
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    discount_amount DECIMAL(15,2) DEFAULT 0.00,
    discount_percentage DECIMAL(5,2) DEFAULT 0.00,
    tax_amount DECIMAL(15,2) DEFAULT 0.00,
    total_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    
    -- Cash Payment
    cash_received DECIMAL(15,2),
    cash_change DECIMAL(15,2),
    
    -- Member Points
    points_earned INT DEFAULT 0,
    points_used INT DEFAULT 0,
    
    -- HPP Calculation
    total_hpp DECIMAL(15,2) DEFAULT 0.00, -- Total Harga Pokok Penjualan
    gross_profit DECIMAL(15,2) DEFAULT 0.00, -- Laba Kotor
    
    notes TEXT,
    created_by UUID, -- References user_id (UUID)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_transactions_updated_at
    BEFORE UPDATE ON transactions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_transactions_business_id ON transactions(business_id);
CREATE INDEX idx_transactions_member_id ON transactions(member_id);
CREATE INDEX idx_transactions_number ON transactions(transaction_number);
CREATE INDEX idx_transactions_date ON transactions(transaction_date);
CREATE INDEX idx_transactions_payment_method ON transactions(payment_method);
CREATE INDEX idx_transactions_business_date ON transactions(business_id, transaction_date);
CREATE INDEX idx_transactions_member_status ON transactions(member_id, payment_status);


CREATE TABLE transaction_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    
    -- Item Details
    product_name VARCHAR(255) NOT NULL, -- Snapshot nama produk
    quantity DECIMAL(10,2) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    
    -- Pricing
    purchase_price DECIMAL(15,2) NOT NULL, -- HPP per unit (snapshot)
    selling_price DECIMAL(15,2) NOT NULL,  -- Harga jual per unit
    
    -- Calculations
    subtotal DECIMAL(15,2) NOT NULL, -- quantity * selling_price
    hpp_total DECIMAL(15,2) NOT NULL, -- quantity * purchase_price
    profit DECIMAL(15,2) NOT NULL, -- subtotal - hpp_total
    
    notes TEXT
);

CREATE INDEX idx_transaction_items_trx_id ON transaction_items(transaction_id);
CREATE INDEX idx_transaction_items_product_id ON transaction_items(product_id);

-- =====================================================
-- 9. TABEL EXPENSES (Biaya Operasional)
-- =====================================================

CREATE TABLE expense_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_expense_categories_business_id ON expense_categories(business_id);

CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    expense_category_id BIGINT REFERENCES expense_categories(id) ON DELETE SET NULL,
    
    -- Expense Info
    name VARCHAR(255) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    expense_date DATE NOT NULL,
    
    -- Recurrence
    is_recurring BOOLEAN DEFAULT FALSE,
    recurrence_period recurrence_period_enum,
    
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_expenses_updated_at
    BEFORE UPDATE ON expenses
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_expenses_business_id ON expenses(business_id);
CREATE INDEX idx_expenses_date ON expenses(expense_date);
CREATE INDEX idx_expenses_category_id ON expenses(expense_category_id);

-- =====================================================
-- 10. TABEL REPORTS CACHE (untuk performa)
-- =====================================================

CREATE TABLE daily_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    report_date DATE NOT NULL,
    
    -- Sales
    total_transactions INT DEFAULT 0,
    total_sales DECIMAL(15,2) DEFAULT 0.00,
    total_discount DECIMAL(15,2) DEFAULT 0.00,
    
    -- HPP & Profit
    total_hpp DECIMAL(15,2) DEFAULT 0.00,
    gross_profit DECIMAL(15,2) DEFAULT 0.00,
    gross_margin DECIMAL(5,2) DEFAULT 0.00,
    
    -- Expenses
    total_expenses DECIMAL(15,2) DEFAULT 0.00,
    net_profit DECIMAL(15,2) DEFAULT 0.00,
    net_margin DECIMAL(5,2) DEFAULT 0.00,
    
    -- Items
    total_items_sold INT DEFAULT 0,
    
    -- Members
    total_member_transactions INT DEFAULT 0,
    new_members_count INT DEFAULT 0,
    
    -- Payment Methods
    cash_transactions DECIMAL(15,2) DEFAULT 0.00,
    digital_transactions DECIMAL(15,2) DEFAULT 0.00,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    UNIQUE (business_id, report_date)
);

CREATE TRIGGER update_daily_reports_updated_at
    BEFORE UPDATE ON daily_reports
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_daily_reports_business_id ON daily_reports(business_id);
CREATE INDEX idx_daily_reports_date ON daily_reports(report_date);

-- =====================================================
-- 11. TABEL SETTINGS & PREFERENCES
-- =====================================================

CREATE TYPE setting_type_enum AS ENUM ('string', 'number', 'boolean', 'json');

CREATE TABLE business_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT,
    setting_type setting_type_enum DEFAULT 'string',
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    UNIQUE (business_id, setting_key)
);

CREATE TRIGGER update_business_settings_updated_at
    BEFORE UPDATE ON business_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_business_settings_business_id ON business_settings(business_id);

-- =====================================================
-- 12. TABEL NOTIFICATIONS & REMINDERS
-- =====================================================

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, -- References UUID
    
    -- Notification Details
    type notification_type_enum NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    
    -- Related Data
    related_type VARCHAR(50), -- 'product', 'transaction', 'member'
    related_id BIGINT,
    
    -- Status
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMP WITH TIME ZONE,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_notifications_business_id ON notifications(business_id);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_is_read ON notifications(is_read);

-- =====================================================
-- 13. TABEL AUDIT LOG (Track semua perubahan penting)
-- =====================================================

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    user_id UUID, -- References UUID
    
    -- Action Details
    action VARCHAR(50) NOT NULL, -- 'create', 'update', 'delete'
    table_name VARCHAR(50) NOT NULL,
    record_id BIGINT,
    
    -- Changes
    old_values JSONB, -- Changed to JSONB for Postgres
    new_values JSONB,
    
    ip_address VARCHAR(45),
    user_agent TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_audit_logs_business_id ON audit_logs(business_id);
CREATE INDEX idx_audit_logs_table_name ON audit_logs(table_name);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);

-- =====================================================
-- 14. TABEL PROMO & DISCOUNTS
-- =====================================================

CREATE TABLE promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    
    -- Promo Details
    name VARCHAR(255) NOT NULL,
    description TEXT,
    promo_code VARCHAR(50),
    
    -- Discount
    discount_type discount_type_enum NOT NULL,
    discount_value DECIMAL(15,2) NOT NULL,
    
    -- Conditions
    min_purchase DECIMAL(15,2) DEFAULT 0.00,
    max_discount DECIMAL(15,2),
    
    -- Target
    target_member_level VARCHAR(50) DEFAULT 'all', -- Simplified for enum matching
    applicable_products JSONB, -- Array of product IDs
    
    -- Validity
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    max_usage INT,
    current_usage INT DEFAULT 0,
    
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TRIGGER update_promotions_updated_at
    BEFORE UPDATE ON promotions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_promotions_business_id ON promotions(business_id);
CREATE INDEX idx_promotions_promo_code ON promotions(promo_code);
CREATE INDEX idx_promotions_dates ON promotions(start_date, end_date);

-- =====================================================
-- 15. TABEL MEMBER POINTS HISTORY
-- =====================================================

CREATE TABLE member_points_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    transaction_id BIGINT REFERENCES transactions(id) ON DELETE SET NULL,
    
    -- Points Details
    points_change INT NOT NULL, -- Positive for earn, negative for redeem
    points_before INT NOT NULL,
    points_after INT NOT NULL,
    
    -- Reason
    type member_points_type_enum NOT NULL,
    description TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_member_points_member_id ON member_points_history(member_id);
CREATE INDEX idx_member_points_created_at ON member_points_history(created_at);

-- =====================================================
-- 16. TABEL ACTIVATION CODES
-- =====================================================

CREATE TABLE activation_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) UNIQUE NOT NULL,
    
    -- Assignment
    assigned_to_phone VARCHAR(20),
    assigned_at TIMESTAMP WITH TIME ZONE,
    
    -- Status
    is_used BOOLEAN DEFAULT FALSE,
    used_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL, -- References UUID
    used_at TIMESTAMP WITH TIME ZONE,
    
    -- Management
    created_by VARCHAR(100), -- 'system', 'admin', 'partner'
    partner_name VARCHAR(255), -- Nama partner UMKM
    
    expires_at TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_activation_codes_code ON activation_codes(code);
CREATE INDEX idx_activation_codes_assigned_phone ON activation_codes(assigned_to_phone);
CREATE INDEX idx_activation_codes_is_used ON activation_codes(is_used);

-- =====================================================
-- VIEWS
-- =====================================================

CREATE OR REPLACE VIEW v_low_stock_products AS
SELECT 
    p.id,
    p.business_id,
    p.name,
    p.stock_quantity,
    p.min_stock,
    p.unit,
    p.selling_price,
    c.name as category_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.stock_quantity <= p.min_stock
  AND p.is_active = TRUE;

CREATE OR REPLACE VIEW v_top_products AS
SELECT 
    p.id,
    p.business_id,
    p.name,
    COUNT(ti.id) as times_sold,
    SUM(ti.quantity) as total_quantity_sold,
    SUM(ti.subtotal) as total_revenue,
    SUM(ti.profit) as total_profit
FROM products p
INNER JOIN transaction_items ti ON p.id = ti.product_id
INNER JOIN transactions t ON ti.transaction_id = t.id
WHERE t.payment_status = 'paid'
GROUP BY p.id, p.business_id, p.name;

CREATE OR REPLACE VIEW v_member_stats AS
SELECT 
    m.id,
    m.business_id,
    m.name,
    m.phone,
    m.member_level,
    m.total_points,
    COUNT(DISTINCT t.id) as total_transactions,
    COALESCE(SUM(t.total_amount), 0) as total_spending,
    COALESCE(AVG(t.total_amount), 0) as avg_transaction
FROM members m
LEFT JOIN transactions t ON m.id = t.member_id AND t.payment_status = 'paid'
GROUP BY m.id, m.business_id, m.name, m.phone, m.member_level, m.total_points;

-- =====================================================
-- TRIGGERS & FUNCTIONS FOR AUTOMATION
-- =====================================================

-- 1. Auto-update product stock after transaction
CREATE OR REPLACE FUNCTION fn_after_transaction_item_insert()
RETURNS TRIGGER AS $$
BEGIN
    -- Decrease stock
    UPDATE products
    SET stock_quantity = stock_quantity - NEW.quantity
    WHERE id = NEW.product_id;
    
    -- Record stock movement
    -- Note: We need to fetch current product details for the movement record
    INSERT INTO stock_movements (
        business_id,
        product_id,
        movement_type,
        quantity,
        purchase_price_per_unit,
        selling_price_per_unit,
        reference_type,
        reference_id,
        stock_before,
        stock_after,
        movement_date,
        created_by
    )
    SELECT 
        p.business_id,
        NEW.product_id,
        'sale',
        -NEW.quantity,
        NEW.purchase_price,
        NEW.selling_price,
        'transaction',
        NEW.transaction_id,
        p.stock_quantity + NEW.quantity, -- Revert the subtraction to get 'before'
        p.stock_quantity,
        NOW(),
        NULL -- System triggered
    FROM products p
    WHERE p.id = NEW.product_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_after_transaction_item_insert
    AFTER INSERT ON transaction_items
    FOR EACH ROW
    EXECUTE FUNCTION fn_after_transaction_item_insert();

-- 2. Update member stats after transaction
CREATE OR REPLACE FUNCTION fn_after_transaction_insert()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.member_id IS NOT NULL AND NEW.payment_status = 'paid' THEN
        UPDATE members
        SET 
            total_transactions = total_transactions + 1,
            total_spending = total_spending + NEW.total_amount,
            total_points = total_points + NEW.points_earned - NEW.points_used
        WHERE id = NEW.member_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_after_transaction_insert
    AFTER INSERT ON transactions
    FOR EACH ROW
    EXECUTE FUNCTION fn_after_transaction_insert();

-- 3. Auto-generate transaction number
CREATE OR REPLACE FUNCTION fn_generate_transaction_number()
RETURNS TRIGGER AS $$
DECLARE
    daily_count INT;
BEGIN
    IF NEW.transaction_number IS NULL OR NEW.transaction_number = '' THEN
        -- Get count of transactions for this business today
        SELECT COUNT(*) INTO daily_count
        FROM transactions 
        WHERE business_id = NEW.business_id 
          AND DATE(transaction_date) = DATE(NEW.transaction_date);

        -- Format: INV-YYYYMMDD-0000
        NEW.transaction_number := 'INV-' || TO_CHAR(NEW.transaction_date, 'YYYYMMDD') || '-' || LPAD((daily_count + 1)::TEXT, 4, '0');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_before_transaction_insert
    BEFORE INSERT ON transactions
    FOR EACH ROW
    EXECUTE FUNCTION fn_generate_transaction_number();

-- =====================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE businesses ENABLE ROW LEVEL SECURITY;
-- (Add other tables here)

-- Users Policy: Can see their own data
CREATE POLICY "Users can view their own data" ON users
  FOR SELECT USING (auth.uid() = auth_id);

-- Super Admin Policy: Can view all
CREATE POLICY "Super Admins can view all users" ON users
  FOR ALL USING (
    (SELECT role FROM users WHERE auth_id = auth.uid()) = 'super_admin'
  );

-- =====================================================
-- SEED DATA
-- =====================================================

-- Just an example, real seeding happens via App
